In [1]:
print("Hello world of python Day 19 !!!")

Hello world of python Day 19 !!!


In [3]:
!pip install numpy

In [5]:

import numpy as np


In [6]:
array_one = np.array([1,2,3,4,5])

array_one

array([1, 2, 3, 4, 5])

In [7]:
type(array_one)    # it is showing as numpy array

numpy.ndarray

In [9]:
numbers =[5,6,7,8.9,15]  # defaultly the representation of the no's in numpy is float (multi dimensional array)

array_two=np.array(numbers)

array_two

array([ 5. ,  6. ,  7. ,  8.9, 15. ])

In [ ]:
req:create an array of zersos with desired shapes(x,y)
    
    x:no of rows
    y:no of cols

In [14]:
array_1=np.zeros((3,4))   

array_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
type(array_1)

numpy.ndarray